GH-115 Fix death cause
EternalCodeTeam/EternalCombat pull request #119
Opened 2023-10-09 21:30 UTC by imDMK

Fixes #115

2023-10-10 06:43 UTC, vLuckyyy approved these changes

2023-10-14 20:01 UTC, Jakubk15 approved these changes

2023-10-14 20:04 UTC, Rollczi approved these changes

2023-10-14 20:05 UTC, Rollczi requested changes
Resolve merge conflicts please :trollface:

2023-10-19 17:26 UTC, merged