Centralized Dependency and Project Configuration Management.
EternalCodeTeam/EternalCombat pull request #126
Opened 2023-10-19 19:10 UTC by vLuckyyy

# Using `libs.versions.toml` for Central Dependency Management

The purpose of this pull request is to establish a more organized dependency management structure in our Gradle project by introducing the use of `libs.versions.toml`

## Details

We have created the `libs.versions.toml` file in the `gradle/` directory, which is the main project directory. This file helps us define all dependency versions in one place, significantly reducing redundancy and simplifying library updates.

### For library:
![obraz](https://github.com/EternalCodeTeam/EternalCombat/assets/65517973/084e200b-da23-4bb6-82e9-102af1ca4ca6)

### For gradle plugin:
![Bez tytułu](https://github.com/EternalCodeTeam/EternalCombat/assets/65517973/0a083bbc-8c47-411a-b3d4-13abc6c3b3bd)

## Benefits

- **Central Dependency Management**: All library versions are now defined in a single `libs.versions.toml` file. This streamlines version management and helps keep the project up to date.

- **Redundancy Elimination**: Previously, the same versions and dependencies had to be defined in multiple places, leading to redundancy and making management more challenging. Now, we all rely on a single source of truth.

## Conclusions

These changes simplify dependency and configuration management in our Gradle project. Now, when we want to update a library version, we only need to change it in one place, and this change automatically propagates to all modules using it. This is an official and recommended Gradle feature, as per the [Gradle documentation](https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml). This model is much more sustainable and easier to manage in the long run. 🚀💡

2023-10-19 19:15 UTC, Jakubk15 approved these changes

2023-10-19 19:19 UTC, Rollczi requested changes
centralizacja jak w starym dobry komunizmie

2023-10-19 19:19 UTC, Rollczi commented on eternalcombat-api/build.gradle.kts
> -publishing {
czemu publish zostało usunięte?

2023-10-19 19:19 UTC, Rollczi commented on gradle/libs.versions.toml
> +runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper" }
teraz żeby prześledzić jakiekolwiek zależności per moduł to trzeba zaglądać ciągle do tego pliku. jedyne co by mogło mieć sens to wersjonowanie ale takie coś to przesada kompletnie

2023-10-19 19:19 UTC, Rollczi commented on build.gradle.kts
> +}
nie musisz tego centralizować, po prostu dodaj konwencje w `buildSrc`

2023-10-19 21:06 UTC, imDMK approved these changes

2023-10-21 13:09 UTC, vLuckyyy reviewed
I will merge it, I understand that not everyone likes this convention, we will introduce any corrections in separate pull requests, currently the gradle setup on the master is not done properly, **so it prevents any work on the plugin.**

2023-10-21 13:10 UTC, merged