Knockback rework
EternalCodeTeam/EternalCombat pull request #179
Opened 2024-08-28 19:19 UTC by CitralFlo

Fix

2024-08-28 19:49 UTC, Rollczi commented on eternalcombat-api/src/main/java/com/eternalcode/combat/region/RegionController.java
> +        this.knockbackMultiplier = this.pluginConfig.settings.blockedRegionKnockMultiplier;
You should use variable directly from plugin  config.

2024-09-02 14:50 UTC, P1otrulla commented on eternalcombat-api/src/main/java/com/eternalcode/combat/notification/NotificationAnnouncer.java
> +            else {
Not needed else block

2024-09-02 14:50 UTC, P1otrulla commented on eternalcombat-api/src/main/java/com/eternalcode/combat/notification/NotificationAnnouncer.java
> +    private final HashMap<UUID, Instant> timeLimitMap = new HashMap<>();
Im not sure is good place for holding this

2024-09-02 14:50 UTC, P1otrulla commented on eternalcombat-api/src/main/java/com/eternalcode/combat/notification/NotificationAnnouncer.java
> +    public void sendMessage(Player player, String text, Duration timeLimit) {
You can just copypaste from EternalCore  Delay class end hold this in listener or specific manager for that

2024-09-03 09:44 UTC, imDMK requested changes

2024-09-03 09:44 UTC, imDMK commented on eternalcombat-api/src/main/java/com/eternalcode/combat/notification/NotificationAnnouncer.java
> +    private final HashMap<UUID, Instant> timeLimitMap = new HashMap<>();
This should be in a different class. Maybe RegionKnockbackService

2024-09-03 09:44 UTC, imDMK commented on eternalcombat-api/src/main/java/com/eternalcode/combat/notification/NotificationAnnouncer.java
> +    public void sendMessage(Player player, String text, Duration timeLimit) {
^

2024-09-03 09:44 UTC, imDMK commented on eternalcombat-api/src/main/java/com/eternalcode/combat/region/WorldGuardRegionProvider.java
> +        ProtectedRegion combatRegion = null;
Maybe use AtomicReference?
```suggestion
        AtomicReference<ProtectedRegion> combatRegion = new AtomicReference<ProtectedRegion>();
```

2024-09-18 21:15 UTC, closed without merging