Fix some problematic things.
EternalCodeTeam/EternalCombat pull request #43
Opened 2023-02-15 02:04 UTC by vLuckyyy

2023-02-15 22:50 UTC, eripe14 approved these changes
Wygląda okej. Bardzo dobra robota Lucjuszu Lackijuszu. Tak trzymac!

2023-02-18 20:14 UTC, Jakubk15 approved these changes
Chcę Cię pochwalić za doskonałą pracę nad kodem. Przeglądając Twój PR, nie zauważyłem żadnych poważnych problemów i jestem pod wrażeniem jakości Twojego kodu.

Ogólnie, bardzo Cię pochwalam za Twój wkład w projekt i jestem przekonany, że Twoja praca przyniesie wiele korzyści. Ewentualnie w pliku `gradle.yml` możesz ustawić wcięcia na 2 w `.editorconfig`.

2023-02-22 01:51 UTC, Rollczi requested changes
Ja bym zrobił revert na combat (znaczenie słowa ma więcej sensu w tym kontekście niż fight) 
+nadal istnieje i jest używane getEnemy() co jest błędne bo nigdzie nie jest zapisywany walczący i ofiara.

2023-02-22 17:12 UTC, eripe14 requested changes

2023-02-22 17:12 UTC, eripe14 commented on src/main/java/com/eternalcode/combat/fight/FightManager.java
> +    }
nie można tutaj po prostu użyć metody contains?

2023-02-22 21:12 UTC, eripe14 approved these changes
Według mnie, lucky zrobił solidną robotę. Poprawił ładnie logikę kodu. Zasługuję na approve oraz dużego kebaba.

2023-02-22 21:38 UTC, Rollczi requested changes

2023-02-22 21:38 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/CombatCommand.java
> +        if (target == null) {
do wywalenia

2023-02-22 22:21 UTC, Rollczi approved these changes

2023-02-22 22:53 UTC, merged