Add blocking damage causes feature
EternalCodeTeam/EternalCombat pull request #47
Opened 2023-02-25 23:22 UTC by eripe14

2023-02-25 23:54 UTC, Rollczi requested changes
Wystarczy zmienić to co jest w Tag Controller

2023-02-26 07:38 UTC, Jakubk15 approved these changes
Dostosuj się do zaleceń Rollcziego

2023-02-26 07:38 UTC, Jakubk15 commented on src/main/java/com/eternalcode/combat/config/implementation/PluginConfig.java
> +            .add(EntityDamageEvent.DamageCause.FALL)
defaultowo wywaliłbym FALL

2023-02-26 18:08 UTC, vLuckyyy requested changes

2023-02-26 18:08 UTC, vLuckyyy commented on src/main/java/com/eternalcode/combat/config/implementation/PluginConfig.java
> +        public List<EntityDamageEvent.DamageCause> damageCauses = new ImmutableList.Builder<EntityDamageEvent.DamageCause>()
Domyślnie daj lawa, mob, fire i ewentualnie obrażenia od np. kaktusa itd, oraz opisz w komentarzu że jak ktoś nie chce czegoś to żeby usunął z listy po prostu.

2023-03-02 10:24 UTC, Osnixer approved these changes

2023-03-02 17:20 UTC, vLuckyyy approved these changes

2023-03-02 17:20 UTC, merged