Add potion effects in combatlog
EternalCodeTeam/EternalCombat pull request #58
Opened 2023-04-07 18:47 UTC by eripe14

2023-04-07 19:13 UTC, Jakubk15 approved these changes

2023-04-07 19:13 UTC, Jakubk15 commented on src/main/java/com/eternalcode/combat/config/implementation/PluginConfig.java
> +        @Description({ " ", "# What potion effects should the player get after getting the combatlog?",
```suggestion
        @Description({ " ", "# What potion effects should the player get after getting tagged?",
```

2023-04-07 19:13 UTC, Jakubk15 commented on src/main/java/com/eternalcode/combat/config/implementation/PluginConfig.java
> +        @Description({ " ", "# Whether the player should get potion effects during the combatlog?" })
```suggestion
        @Description({ " ", "# Whether the player should get potion effects during combat?" })
```

2023-04-07 19:13 UTC, Jakubk15 commented on src/main/java/com/eternalcode/combat/config/implementation/PluginConfig.java
> +        "# Amplifier zero is in minecraft one, one is two etc.  " })
```suggestion
        "# Amplifiers in Minecraft start with number 0, so one is zero, etc. " })
```

2023-04-16 19:10 UTC, Osnixer approved these changes

2023-04-16 19:38 UTC, vLuckyyy requested changes
Poziom efektu się duplikuje, jeżeli bez walki wypije potke Jump boost 1 i w configu combata jest ustawione Jump Boost 2 to podczas walki bede mial jump boost 3 

https://user-images.githubusercontent.com/65517973/232337750-ffdac0e1-780f-4b63-8f17-f3e726d6ed69.mov

2023-04-16 19:42 UTC, vLuckyyy requested changes
Dodatkowo, jeżeli gracz wypije potke podczas walki, to nie otrzyma jej a zostanie mu ona usunieta z eq, proponuje byś dodał opcje w configu która mówi o tym czy gracz ma możliwość picia potek podczas walki i opisz ładnie że jeżeli opcja będzie wyłączona czyli będzie mógł pić potki to że będą one przechowywane i zostaną dodane graczowi po zakończeniu walki
https://user-images.githubusercontent.com/65517973/232337966-b4ad2234-5dc7-4af0-b69d-8a975287f768.mov

2023-04-17 19:45 UTC, Rollczi requested changes
Domena potion powinna nasłuchiwać eventów domeny fight ale nie wpychać się do jego kontrollerów. Jeszcze parę ficzerów i się zrobi syf jak tak to zostanie. Proszę dodać eventy dla fight i nasłuchiwać ich.

2023-04-17 19:45 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/FightTask.java
> +            this.fightPotionEffectManager.restorePotionEffects(player);
Proszę tutaj tego nie wpychać, miały być callowane eventy od untag i potion effect miały je nasłuchiwać

2023-04-17 19:45 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/controller/FightTagController.java
> +    private final FightPotionEffectManager fightPotionEffectManager;
Proszę nie wpychać tutaj potion

2023-09-30 20:00 UTC, closed without merging

2023-09-30 20:00 UTC, CitralFlo commented
Closed due to https://github.com/EternalCodeTeam/EternalCombat/pull/116