Add pearl delay in combat
EternalCodeTeam/EternalCombat pull request #77
Opened 2023-06-16 14:44 UTC by imDMK

This PR adds ender pearl throw delay.
Fixes #50.

Tested on localhost server.

2023-06-24 12:06 UTC, vLuckyyy approved these changes

2023-06-24 19:06 UTC, Rollczi requested changes
Kod jest bardzo dobrze wykonany i nie mam nic do zarzucenia stricte w samej logice. 

Mam za to jedną architektoniczną uwagę, a więc dodawanie "podficzerów" w domenie `fight` będzie  w przyszłości potęgowało nagromadzenie się dużej ilości mało powiązanego ze sobą kodu. Dla przykładu jakbyśmy chcieli dodać kolejne 10 podobnie tematycznie ficzerów to wszystko by musiałoby siedzieć w `FightTag` i `FightActionBlockerController`

Powiem tak... `FightActionBlockerController` nie jest wykonany idealnie posiada w sobie blokowanie komend, blokowanie budowania itd. co przeczy kompletnie to o czym piszę. Ale z czasem ta klasa zacznie rosnąć do ogromnych rozmiarów i już teraz chciałbym, aby zostało to "rozładowane"

Jeśli chcesz dodać nowy feature to zrób nową paczkę `pearl` i tam dodaj nowy Listener, sekcję do configu + jakąś logikę biznesową jeśli jest to potrzebne

`/fight`
`- FightTag`
`- FightManager`
`/fight/pearl`
`- FightPearlController`
`- FightPearlConfigSection`

2023-06-29 21:13 UTC, shitzuu approved these changes

2023-06-29 21:17 UTC, vLuckyyy approved these changes

2023-06-30 11:10 UTC, Rollczi approved these changes
Jeszcze jak ktoś może niech sprawdzi czy w settings są ok komentarze po angielsku

2023-06-30 11:38 UTC, vLuckyyy approved these changes

2023-06-30 11:38 UTC, vLuckyyy commented on src/main/java/com/eternalcode/combat/fight/pearl/FightPearlSettings.java
> +    public boolean enabled = true;
```suggestion
    @Description("# If you want to completely disable this option, set this to false")
    public boolean enabled = true;
```

2023-06-30 13:10 UTC, Jakubk15 approved these changes

2023-07-01 10:24 UTC, merged