Add worldguard line
EternalCodeTeam/EternalCombat pull request #79
Opened 2023-06-23 21:41 UTC by Osnixer

**Please describe the changes made by this PR and why they need to be merged:**

2023-06-24 10:38 UTC, Kamicjusz approved these changes

2023-06-24 13:30 UTC, igoyek approved these changes

2023-06-24 13:32 UTC, vLuckyyy approved these changes

2023-06-24 16:03 UTC, Rollczi requested changes
Kodzik ma system ładowania hooków ale tak ostatecznie to nie jest soft dependency, przydało by się zrobić jakiś interface RegionProvider i zrobić impl dla WG oraz pustą implke.

2023-06-24 16:03 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/region/RegionService.java
> +    private final WorldGuardBridge worldGuardBridge;
Przydało by się tutaj zastosować odwrócenie zależności, aby domena nie dotykała WG i WE

2023-06-24 19:06 UTC, eripe14 approved these changes
zastosuj się jedynie do poprawek rollcziego

2023-06-24 19:26 UTC, Jakubk15 approved these changes

2023-06-24 19:26 UTC, Jakubk15 commented on src/main/java/com/eternalcode/combat/config/implementation/PluginConfig.java
> +        public double blockedRegionMultiply = 1.2;
Zmień nazwę na blockedRegionMultiplier

2023-06-24 19:26 UTC, Jakubk15 commented
Jak wyżej, zastosuj się do poprawek Rollcziego

2023-06-27 23:18 UTC, Rollczi approved these changes

2023-06-27 23:18 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/bridge/BridgeService.java
> +import com.sk89q.worldguard.WorldGuard;
^

2023-06-27 23:34 UTC, merged