Add DropModifier implementation.
EternalCodeTeam/EternalCombat pull request #89
Opened 2023-07-02 20:04 UTC by failutee

#88 Nowy PR bo coś się zepsuło i nie mogłem commitować

2023-07-03 13:57 UTC, Osnixer approved these changes

2023-07-04 14:01 UTC, Jakubk15 approved these changes

2023-07-05 18:11 UTC, Rollczi requested changes

2023-07-05 18:13 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/util/MathUtil.java
> +        return (percentage / 100D) * totalCount;
z drugiej strony pomaga czytać kolejność działań matematycznych.

2023-07-05 18:14 UTC, failutee commented on src/main/java/com/eternalcode/combat/util/MathUtil.java
> +        return (percentage / 100D) * totalCount;
To zostawić nawias?

2023-07-06 14:57 UTC, Rollczi approved these changes

2023-07-06 15:04 UTC, vLuckyyy approved these changes

2023-07-10 16:32 UTC, merged