Add build instructions
EternalCodeTeam/EternalCombat pull request #91
Opened 2023-07-18 20:41 UTC by NotAlexNoyle

**Please describe the changes made by this PR and why they need to be merged:**

Without running the shadowJar task manually, the output Jar is not linked correctly with all of its required libraries.

2023-07-19 05:31 UTC, Rollczi approved these changes

2023-07-19 15:47 UTC, eripe14 approved these changes

2023-07-20 20:48 UTC, Jakubk15 requested changes
If I recall correctly, the `shadowJar` task depends on `build`, therefore it is not required to run it, as we do in our other projects

2023-07-20 20:48 UTC, Jakubk15 commented on README.md
> +./gradlew shadowJar && ./gradlew build
```suggestion
`./gradlew shadowJar`
```

2023-07-23 12:14 UTC, Jakubk15 approved these changes

2023-07-23 12:14 UTC, merged