GH-98 Pearl throw control
EternalCodeTeam/EternalCombat pull request #99
Opened 2023-08-07 16:33 UTC by imDMK

Add an option to the configuration whether the player should receive combat status and damage after pearl throw.
Tested on localhost.
Fixes #98.

2023-08-08 09:08 UTC, Jakubk15 approved these changes

2023-08-10 04:59 UTC, Rollczi requested changes
Trochę do poprawy jest, jakbyś miał jakieś pytania to chętnie pomogę tu lub na discordzie :P

2023-08-10 04:59 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/pearl/FightPearlController.java
> +            event.setCancelled(true);
Rozumiem, co chcesz zrobić i że to działa. W pewnych warunkach modyfikowanie flow eventu i sztuczne przyznawanie damage graczowi może mieć potencjalne skutki uboczne typu:
~Gracz dostaje damage od pereł na chronionym regionie.
~System rankingu gildii nie uwzględnia odpowiednio tego damagr do asyst. 

Proponuję inne rozwiązanie. 
Dodaj listę zablokowanych entity które nie będą przyznawał taga. Np. ARROW, PEARL. Będzie to już raczej w tych głównych ficzerach.

2023-08-10 04:59 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/pearl/FightPearlController.java
> +                event.setDamage(0.0D);
Jeśli chodzi o tego feature to, można go zrobić w innym listenerze który ignoruje anulowane eventy i słucha na HIGHEST.
Pozwoli to na dobry flow zgrany z takimi pluginami od regionów itd. 

De fakto będzie to polegać na setDamage(0.0D) bez konieczności symulowania obrażeń

2023-08-11 16:53 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/config/implementation/PluginConfig.java
> +        );
samych graczy nie ma co blokować bo to jedyne entity które tagują bezpośrednio lub pośrednio (przez projectile)
ogólnie lepiej odwrócić działanie, tego żeby była to black lista dla "pocisków" (perły strzały itd) `disabledTagEntites`


```suggestion
        @Description({
            "# After what type of projectile entity should not tag the player as fighter?",
            "# You can find a list of all entity types here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html"
        public List<EntityType> disabledProjectileEntites = List.of(
            EntityType.ENDER_PEARL
        );
```

2023-08-11 16:53 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/controller/FightTagController.java
> +        }
Teraz można sprawdzić czy dany pocisk jest na blacklist i w razie czego zreturnować metodę 

```suggestion
        List<EntityType> disabledProjectileEntites = this.config.settings.disabledProjectileEntites;
        
        if (event.getDamager() instanceof Projectile projectile && disabledProjectileEntites.contains(projectile.getType())) {
            return;
        }
```

2023-08-11 16:53 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/pearl/FightPearlSettings.java
> +    public boolean pearlThrowControlEnabled = true;
```suggestion
    @Description("# Set true, If you want to lock pearls during the combat")
    public boolean pearlThrowBlocked = false;
```

2023-08-11 16:53 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/pearl/FightPearlController.java
> +
W sumie pearlThrowDamageEnabled może być niezależny
```suggestion
```

2023-08-11 16:53 UTC, Rollczi commented on src/main/java/com/eternalcode/combat/fight/pearl/FightPearlSettings.java
> +    public Duration pearlThrowDelay = Duration.ofSeconds(3);
daj to 1 opcje wyżej

2023-08-17 10:15 UTC, Rollczi approved these changes

2023-08-17 18:16 UTC, vLuckyyy approved these changes

2023-08-19 16:10 UTC, merged